wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691782025.481017
    t:
      1:
      - 1
      - 5
      - 33
      - 53
      - 55
      - 86
      - 95
      2:
      - 1
      - 5
      - 33
      - 53
      - 55
      - 86
      - 95
      3:
      - 2
      - 13
      - 15
      - 23
      4: 3.9.16
      5: 0.15.8
      8:
      - 1
      - 4
      - 5
